import { Prisma, type PrismaClient } from '../../generated/prisma/client.js';
import type { CostAllocationRuleInput, ICostAllocationRepository } from '../../domain/interfaces/ICostAllocationRepository.js';
import type { AllocationPreview, AllocationSummary, CostAllocationRule, CostAllocationRuleStatus, UnallocatedCostDetail } from '../../domain/models/CostAllocation.js';

type Metric = { readonly billedCost: Prisma.Decimal; readonly billingCurrency: string; readonly cloudAccountId: string; readonly provider: string; readonly serviceName: string; readonly regionId: string | null; readonly resourceId: string; readonly tags: unknown };

export class PrismaCostAllocationRepository implements ICostAllocationRepository {
  constructor(private readonly prisma: PrismaClient) {}

  public async listRules(tenantId: string, status?: CostAllocationRuleStatus): Promise<readonly CostAllocationRule[]> {
    return (await this.prisma.costAllocationRule.findMany({ where: { tenantId, ...(status === undefined ? {} : { status }) }, orderBy: [{ priority: 'asc' }, { createdAt: 'asc' }] })).map(toRule);
  }
  public async findRule(tenantId: string, ruleId: string): Promise<CostAllocationRule | null> { const row = await this.prisma.costAllocationRule.findFirst({ where: { tenantId, id: ruleId } }); return row === null ? null : toRule(row); }
  public async createRule(tenantId: string, userId: string, input: CostAllocationRuleInput): Promise<CostAllocationRule> { return toRule(await this.prisma.costAllocationRule.create({ data: { tenantId, createdByUserId: userId, ...defined(input) } })); }
  public async updateRule(tenantId: string, ruleId: string, input: Partial<CostAllocationRuleInput>): Promise<CostAllocationRule | null> { const result = await this.prisma.costAllocationRule.updateMany({ where: { tenantId, id: ruleId, status: { not: 'ARCHIVED' } }, data: defined(input) }); return result.count === 0 ? null : this.findRule(tenantId, ruleId); }
  public async archiveRule(tenantId: string, ruleId: string, now: Date): Promise<CostAllocationRule | null> { const result = await this.prisma.costAllocationRule.updateMany({ where: { tenantId, id: ruleId, status: { not: 'ARCHIVED' } }, data: { status: 'ARCHIVED', archivedAt: now } }); return result.count === 0 ? null : this.findRule(tenantId, ruleId); }
  public async summarize(tenantId: string, periodStart: Date, cloudAccountId?: string, serviceName?: string): Promise<readonly AllocationSummary[]> { const [rules, metrics] = await Promise.all([this.listRules(tenantId, 'ACTIVE'), this.metrics(tenantId, periodStart, cloudAccountId, serviceName)]); return summarize(metrics, rules, periodStart); }
  public async preview(tenantId: string, input: CostAllocationRuleInput, periodStart: Date): Promise<AllocationPreview> { const metrics = await this.metrics(tenantId, periodStart); const rule: CostAllocationRule = { id: 'preview', tenantId, createdByUserId: 'preview', createdAt: periodStart, updatedAt: periodStart, ...input }; const matchingMetrics = metrics.filter((metric) => matches(metric, rule, periodStart)); return { summary: summarize(metrics, [rule], periodStart), metricCount: matchingMetrics.length, resourceCount: new Set(matchingMetrics.map((metric) => metric.resourceId).filter(Boolean)).size, examples: matchingMetrics.slice(0, 5).map((metric) => ({ currency: metric.billingCurrency, cost: Number(metric.billedCost), cloudAccountId: metric.cloudAccountId, serviceName: metric.serviceName, ...(metric.resourceId === '' ? {} : { resourceId: metric.resourceId }) })) }; }
  public async resourceSummary(tenantId: string, resourceId: string): Promise<readonly AllocationSummary[]> {
    const latest = await this.prisma.costMetric.findFirst({ where: { tenantId, resourceId }, orderBy: { chargePeriodStart: 'desc' }, select: { chargePeriodStart: true } });
    if (latest === null) return [];
    const [rules, metrics] = await Promise.all([this.listRules(tenantId, 'ACTIVE'), this.metrics(tenantId, latest.chargePeriodStart, undefined, undefined, resourceId)]);
    return summarize(metrics, rules, latest.chargePeriodStart);
  }
  public async unallocated(tenantId: string, periodStart: Date, currency?: string, cloudAccountId?: string, serviceName?: string): Promise<readonly UnallocatedCostDetail[]> { const [rules, metrics] = await Promise.all([this.listRules(tenantId, 'ACTIVE'), this.metrics(tenantId, periodStart, cloudAccountId, serviceName)]); const groups = new Map<string, UnallocatedCostDetail>(); for (const metric of metrics) { if ((currency !== undefined && metric.billingCurrency !== currency) || matchesAny(metric, rules, periodStart)) continue; const key = [metric.billingCurrency, metric.cloudAccountId, metric.serviceName, metric.resourceId].join('|'); const current = groups.get(key); groups.set(key, { currency: metric.billingCurrency, cost: round((current?.cost ?? 0) + Number(metric.billedCost)), metricCount: (current?.metricCount ?? 0) + 1, ...(metric.resourceId === '' ? {} : { resourceId: metric.resourceId }), serviceName: metric.serviceName, cloudAccountId: metric.cloudAccountId, suggestedCriteria: suggestions(metric) }); } return [...groups.values()].sort((a, b) => b.cost - a.cost); }
  public async writeAudit(tenantId: string, userId: string, action: string, ruleId: string, metadata: unknown): Promise<void> { await this.prisma.auditEvent.create({ data: { tenantId, actorUserId: userId, action, entityType: 'COST_ALLOCATION_RULE', entityId: ruleId, metadata: metadata as Prisma.InputJsonValue } }); }
  // ponytail: this evaluates one tenant-month in memory; move first-match ranking to SQL only when measured monthly volume makes it necessary.
  private async metrics(tenantId: string, periodStart: Date, cloudAccountId?: string, serviceName?: string, resourceId?: string): Promise<readonly Metric[]> { const end = new Date(Date.UTC(periodStart.getUTCFullYear(), periodStart.getUTCMonth() + 1, 1)); return this.prisma.costMetric.findMany({ where: { tenantId, chargePeriodStart: { gte: periodStart, lt: end }, ...(cloudAccountId === undefined ? {} : { cloudAccountId }), ...(serviceName === undefined ? {} : { serviceName }), ...(resourceId === undefined ? {} : { resourceId }) }, select: { billedCost: true, billingCurrency: true, cloudAccountId: true, provider: true, serviceName: true, regionId: true, resourceId: true, tags: true } }); }
}

export function summarize(metrics: readonly Metric[], rules: readonly CostAllocationRule[], periodStart: Date): readonly AllocationSummary[] { const byCurrency = new Map<string, { total: number; allocated: number; groups: Map<string, { cost: number; metricCount: number; resources: Set<string>; rule?: CostAllocationRule }> }>(); for (const metric of metrics) { const bucket = byCurrency.get(metric.billingCurrency) ?? { total: 0, allocated: 0, groups: new Map() }; const rule = matchesAny(metric, rules, periodStart); const key = rule === undefined ? 'UNALLOCATED' : allocationKey(rule); const group = bucket.groups.get(key) ?? { cost: 0, metricCount: 0, resources: new Set<string>(), ...(rule === undefined ? {} : { rule }) }; group.cost += Number(metric.billedCost); group.metricCount += 1; if (metric.resourceId !== '') group.resources.add(metric.resourceId); bucket.total += Number(metric.billedCost); if (rule !== undefined) bucket.allocated += Number(metric.billedCost); bucket.groups.set(key, group); byCurrency.set(metric.billingCurrency, bucket); } return [...byCurrency.entries()].map(([currency, value]) => ({ period: periodStart.toISOString().slice(0, 7), currency, totalCost: round(value.total), allocatedCost: round(value.allocated), unallocatedCost: round(value.total - value.allocated), coveragePercent: value.total === 0 ? 0 : round((value.allocated / value.total) * 100), dimensions: [...value.groups.entries()].map(([allocationKey, group]) => ({ allocationKey, currency, cost: round(group.cost), metricCount: group.metricCount, resourceCount: group.resources.size, ...(group.rule === undefined ? {} : target(group.rule)) })).sort((a, b) => b.cost - a.cost) })); }
function matchesAny(metric: Metric, rules: readonly CostAllocationRule[], period: Date): CostAllocationRule | undefined { return rules.find((rule) => matches(metric, rule, period)); }
function matches(metric: Metric, rule: CostAllocationRule, period: Date): boolean { if (rule.effectiveFrom !== undefined && period < rule.effectiveFrom) return false; if (rule.effectiveTo !== undefined && period > rule.effectiveTo) return false; const tags = asTags(metric.tags); return (rule.cloudAccountId === undefined || rule.cloudAccountId === metric.cloudAccountId) && (rule.provider === undefined || rule.provider === metric.provider) && (rule.serviceName === undefined || rule.serviceName === metric.serviceName) && (rule.regionId === undefined || rule.regionId === metric.regionId) && (rule.resourceId === undefined || rule.resourceId === metric.resourceId) && (rule.tagKey === undefined || tags[rule.tagKey] === rule.tagValue); }
function asTags(value: unknown): Record<string, string> { return typeof value === 'object' && value !== null && !Array.isArray(value) ? Object.fromEntries(Object.entries(value).filter((entry): entry is [string, string] => typeof entry[1] === 'string')) : {}; }
function target(rule: CostAllocationRule) { return { ...(rule.costCenter === undefined ? {} : { costCenter: rule.costCenter }), ...(rule.businessUnit === undefined ? {} : { businessUnit: rule.businessUnit }), ...(rule.project === undefined ? {} : { project: rule.project }), ...(rule.team === undefined ? {} : { team: rule.team }), ...(rule.environment === undefined ? {} : { environment: rule.environment }) }; }
function allocationKey(rule: CostAllocationRule): string { const values = Object.values(target(rule)); return values.length === 0 ? rule.name : values.join(' · '); }
function suggestions(metric: Metric): readonly string[] { return ['Crear regla por servicio', 'Crear regla por cuenta cloud', ...(metric.resourceId === '' ? [] : ['Crear regla por recurso']), ...Object.keys(asTags(metric.tags)).map((key) => `Usar etiqueta: ${key}`)].slice(0, 4); }
function toRule(row: any): CostAllocationRule { return { ...row, description: row.description ?? undefined, cloudAccountId: row.cloudAccountId ?? undefined, provider: row.provider ?? undefined, serviceName: row.serviceName ?? undefined, regionId: row.regionId ?? undefined, resourceId: row.resourceId ?? undefined, tagKey: row.tagKey ?? undefined, tagValue: row.tagValue ?? undefined, costCenter: row.costCenter ?? undefined, businessUnit: row.businessUnit ?? undefined, project: row.project ?? undefined, team: row.team ?? undefined, environment: row.environment ?? undefined, effectiveFrom: row.effectiveFrom ?? undefined, effectiveTo: row.effectiveTo ?? undefined, archivedAt: row.archivedAt ?? undefined }; }
function defined<T extends object>(value: T): { [K in keyof T as T[K] extends undefined ? never : K]: Exclude<T[K], undefined> } { return Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined)) as any; }
function round(value: number): number { return Math.round(value * 100) / 100; }
