import { AuthorizationError, FinOpsBaseError } from '../../domain/errors/errors.js';
import type { CostAllocationRuleInput, ICostAllocationRepository } from '../../domain/interfaces/ICostAllocationRepository.js';
import type { AuthContext } from '../../domain/models/AuthContext.js';
import type { CostAllocationRule, CostAllocationRuleStatus } from '../../domain/models/CostAllocation.js';

const managers = new Set<AuthContext['role']>(['MASTER_ADMIN', 'OPERATOR_ADMIN', 'ADMIN', 'FINOPS_TECHNICIAN']);
const periodPattern = /^\d{4}-(0[1-9]|1[0-2])$/;

export class CostAllocationService {
  constructor(private readonly repository: ICostAllocationRepository) {}
  public async listRules(actor: AuthContext, status?: CostAllocationRuleStatus): Promise<readonly CostAllocationRule[]> { return this.repository.listRules(actor.tenantId, status); }
  public async createRule(actor: AuthContext, input: CostAllocationRuleInput): Promise<CostAllocationRule> { this.requireManager(actor); this.validate(input); const rule = await this.repository.createRule(actor.tenantId, actor.userId, input); await this.repository.writeAudit(actor.tenantId, actor.userId, 'COST_ALLOCATION_RULE_CREATED', rule.id, { status: rule.status, priority: rule.priority }); return rule; }
  public async updateRule(actor: AuthContext, ruleId: string, input: Partial<CostAllocationRuleInput>): Promise<CostAllocationRule> { this.requireManager(actor); const current = await this.requireRule(actor, ruleId); const next = { ...current, ...input }; this.validate(next); const rule = await this.repository.updateRule(actor.tenantId, ruleId, input); if (rule === null) throw new FinOpsBaseError('Allocation rule not found or archived', 'NOT_FOUND'); await this.repository.writeAudit(actor.tenantId, actor.userId, 'COST_ALLOCATION_RULE_UPDATED', rule.id, { status: rule.status, priority: rule.priority }); return rule; }
  public async activateRule(actor: AuthContext, ruleId: string): Promise<CostAllocationRule> { return this.updateRule(actor, ruleId, { status: 'ACTIVE' }); }
  public async archiveRule(actor: AuthContext, ruleId: string): Promise<CostAllocationRule> { this.requireManager(actor); const rule = await this.repository.archiveRule(actor.tenantId, ruleId, new Date()); if (rule === null) throw new FinOpsBaseError('Allocation rule not found or archived', 'NOT_FOUND'); await this.repository.writeAudit(actor.tenantId, actor.userId, 'COST_ALLOCATION_RULE_ARCHIVED', rule.id, {}); return rule; }
  public async preview(actor: AuthContext, input: CostAllocationRuleInput, period: string) { this.requireManager(actor); this.validate(input); return this.repository.preview(actor.tenantId, input, parsePeriod(period)); }
  public async summary(actor: AuthContext, input: { period: string; cloudAccountId?: string; serviceName?: string }) { return this.repository.summarize(actor.tenantId, parsePeriod(input.period), input.cloudAccountId, input.serviceName); }
  public async comparison(actor: AuthContext, input: { period: string; cloudAccountId?: string; serviceName?: string }) { const current = parsePeriod(input.period); const previous = new Date(Date.UTC(current.getUTCFullYear(), current.getUTCMonth() - 1, 1)); const [summary, previousSummary] = await Promise.all([this.repository.summarize(actor.tenantId, current, input.cloudAccountId, input.serviceName), this.repository.summarize(actor.tenantId, previous, input.cloudAccountId, input.serviceName)]); return { summary, previousSummary }; }
  public async unallocated(actor: AuthContext, input: { period: string; currency?: string; cloudAccountId?: string; serviceName?: string }) { return this.repository.unallocated(actor.tenantId, parsePeriod(input.period), input.currency, input.cloudAccountId, input.serviceName); }
  public async resourceSummary(actor: AuthContext, resourceId: string) { return this.repository.resourceSummary(actor.tenantId, resourceId); }
  private async requireRule(actor: AuthContext, ruleId: string): Promise<CostAllocationRule> { const rule = await this.repository.findRule(actor.tenantId, ruleId); if (rule === null) throw new FinOpsBaseError('Allocation rule not found', 'NOT_FOUND'); return rule; }
  private requireManager(actor: AuthContext): void { if (!managers.has(actor.role)) throw new AuthorizationError('You are not allowed to manage allocation rules'); }
  private validate(input: Partial<CostAllocationRuleInput>): void { const criteria = [input.cloudAccountId, input.provider, input.serviceName, input.regionId, input.resourceId, input.tagKey]; const targets = [input.costCenter, input.businessUnit, input.project, input.team, input.environment]; if (criteria.every((value) => value === undefined || value === '')) throw new FinOpsBaseError('At least one allocation criterion is required', 'VALIDATION_ERROR'); if (targets.every((value) => value === undefined || value === '')) throw new FinOpsBaseError('At least one allocation target is required', 'VALIDATION_ERROR'); if (input.tagKey !== undefined && (input.tagValue === undefined || input.tagValue === '')) throw new FinOpsBaseError('A tag value is required when tag key is set', 'VALIDATION_ERROR'); if (input.priority !== undefined && (!Number.isInteger(input.priority) || input.priority < 0)) throw new FinOpsBaseError('Priority must be a non-negative integer', 'VALIDATION_ERROR'); if (input.effectiveFrom !== undefined && input.effectiveTo !== undefined && input.effectiveFrom > input.effectiveTo) throw new FinOpsBaseError('Effective date range is invalid', 'VALIDATION_ERROR'); }
}
function parsePeriod(value: string): Date { if (!periodPattern.test(value)) throw new FinOpsBaseError('Period must be YYYY-MM', 'VALIDATION_ERROR'); const [year, month] = value.split('-').map(Number); return new Date(Date.UTC(year!, month! - 1, 1)); }
